version = 0.1
[default.deploy.parameters]
stack_name = "AI-Incident-Management-System"
resolve_s3 = false
s3_prefix = "AI-Incident-Management-System"
s3_bucket = "sanket-ai-log-alert-system"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []